### ISSUE TITLE
msgpack serialization only works with msgpack-lite 0.1.17

### ISSUE THREAD

**Issue by hefloryd** [crossbario/autobahn-js#197]
For msgpack-lite > 0.1.17, the testsuite fails with:

```
test_msgpack_serialization.js
✖ testMsgpackSerialization

Error: Expected 1 assertions, 0 ran
    at Object.test.done (/home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/types.js:121:25)
    at Object.exports.runTest (/home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:73:14)
    at /home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:118:25
    at /home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:123:13)
    at async.forEachSeries (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:139:9)
    at _concat (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:512:9)
    at Object.concatSeries (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:152:23)
    at Object.exports.runSuite (/home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:96:11)
    at Object.exports.runModule (/home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:158:13)

TypeError: autobahn.serializer.MsgpackSerializer is not a function
    at Object.exports.testMsgpackSerialization (/home/vmadm/autobahn-js/package/test/test_msgpack_serialization.js:24:21)
    at Object.<anonymous> (/home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:236:16)
    at /home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:70:9)
    at /home/vmadm/autobahn-js/package/node_modules/nodeunit/lib/core.js:118:25
    at /home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:123:13)
    at async.forEachSeries (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:139:9)
    at _concat (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:512:9)
    at Object.concatSeries (/home/vmadm/autobahn-js/package/node_modules/nodeunit/deps/async.js:152:23)
```

It appears that the monkey patch to send WAMP IDs as integers is no longer working. On the other hand, the issue that the patch is referencing may be solved? See kawanet/msgpack-lite#1

**Comment by agronholm** [comment]
Looks like it needs another kind of monkey patch now – to convert the WAMP ID to UInt64BE from Number.

**Comment by oberstet** [comment]
Fiyed in v0.11.0
